// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYUW/bNhD+KwS3R9lSbKdp/JalRWpgD0HqPQXGwIgniw1FqiTlzA3834cjbcuy5Nod",
	"liYD9hILIo/33X3fHU95pqkuSq1AOUvHz9SmORTMP14bYA6mzD7ewdcKrMOXpdElGCfAb8mBcTD+kXEu",
	"nNCKydvGFrcsgY6pdUaoOV1FFP5iRSkB164ql2sjvjE0pGM6BevICDetrfTDF0gdvijA5Zqj0dae3nyc",
	"0qjtoDKyuS93rrTjOMbfB6H62szjObi27SqiBr5WwgCn4/uNz3DirAPUboZsqZWFdorEHuj0fcYuhpz3",
	"Buec9UbDi0GPXVxmvez96F2WpHCWprwTWcv7B5BwzDuG/NkxV9lrzaGBZJAk20OFcjAHg6e+HN6Pxmhz",
	"GCrgctO3UAsmBSd/3P1+mosbcFdSYkrsYUcOlz01Dgr/8KuBjI7pL3FdC/G6EOIbcI0U126ZMWx5EMcR",
	"Xo4XzhZdS+BN/42KutbKgXK9qd9yT1lZSpH6+oq/WK3orAvua6kkohLU3OWNs4bJeUQzbQrmgs93I9oF",
	"wXrA3lRVBQar4IlGVKg/S6NTsJZGlGsFNFpra7aTqs3KCaL6BEy6/DCXpTaumY3L5PKsK9o2ZP2I7UWx",
	"BROSPUhoYvSrRxHiK6EyjedysKkR5bqfXt1OSKYNSbFPCTUnn6bTW+L138eThfNu/FvUK7mrlAJDrm4n",
	"NKILMDacc9ZP+gkGoEtQrBR0TIf9pD+kES2Zy31Ece7T9A2fsbm2wNyBq4yyZJAkRCu5JE85KBKsSJpD",
	"+khKxCgssVWK/GWV7JON2XkybFuAwe07+SPahFMyJqQPEpny+p9wDHUNEht94NODHyQJ/qShenxV7hdO",
	"TbC30I/4d8FkBbUGNsRveMZdnp7QTI61mj2hectmDj+DWYgUMOiQhmUfaTlPhj8If1dyJ8Sxu/2lAtrx",
	"0fcyt1VRMLPcshYoR92yucXiCSmgM9wco6pDBLZDfOGmtoQRBU+E2aVKc6OVrmxdE2211Pc7DZMBWPeb",
	"5ssTkn1agtoj1qo5hDhTweofifXHARxmyfcG30SAe8GN/kUIzbGgw/tkPQWsCVgr/qcCcGAUk8SCWYAh",
	"/jbZ12jIpBfSjkTDrFErNH4WfBXkicNbW6hhqLNEq3AWeViSyYe2NOvhzzdhwwpwfqC4f6YCD8LGTCOq",
	"WOHvTU73ZbVbxPt3zOwFJdcxth6SXEjSK0rOM4Dp9wBGPw+AD19pRzJdKf5GJR+Y3JFph/Cj7w8Dx2S+",
	"HqT/axpvfTQcYLhm9395vzl534D7vrY3Td0enXmZlPXY3VL45pOVvqwiW1/Gh4iR4s3essjJNpldlOBu",
	"bx/ahP9fkP++Hcex1CmTubZu7Ofb1Wz1dwAAAP//aNiI2v4SAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
