// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

// Defines values for GetTaskResponseStatus.
const (
	Done      GetTaskResponseStatus = "done"
	Error     GetTaskResponseStatus = "error"
	InProcess GetTaskResponseStatus = "in_process"
	New       GetTaskResponseStatus = "new"
)

// Defines values for HealthResponseStatus.
const (
	Ok          HealthResponseStatus = "ok"
	Unavailable HealthResponseStatus = "unavailable"
)

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Headers *map[string]string `json:"headers,omitempty"`
	Method  string             `json:"method"`
	Url     string             `json:"url"`
}

// CreateTaskResponse defines model for CreateTaskResponse.
type CreateTaskResponse struct {
	Id *string `json:"id,omitempty"`
}

// DeleteTaskResponse defines model for DeleteTaskResponse.
type DeleteTaskResponse struct {
	HttpStatusCode *int    `json:"httpStatusCode,omitempty"`
	Id             *string `json:"id,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// GetAllTasksResponse defines model for GetAllTasksResponse.
type GetAllTasksResponse struct {
	Tasks *[]GetTaskResponse `json:"tasks,omitempty"`
}

// GetTaskResponse defines model for GetTaskResponse.
type GetTaskResponse struct {
	Headers        *map[string][]string   `json:"headers,omitempty"`
	HttpStatusCode *int                   `json:"httpStatusCode,omitempty"`
	Id             *string                `json:"id,omitempty"`
	Length         *int64                 `json:"length,omitempty"`
	Status         *GetTaskResponseStatus `json:"status,omitempty"`
}

// GetTaskResponseStatus defines model for GetTaskResponse.Status.
type GetTaskResponseStatus string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Port   *string               `json:"port,omitempty"`
	Status *HealthResponseStatus `json:"status,omitempty"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequest
