// Package docs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package docs

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for GetTaskResponseStatus.
const (
	Done      GetTaskResponseStatus = "done"
	Error     GetTaskResponseStatus = "error"
	InProcess GetTaskResponseStatus = "in_process"
	New       GetTaskResponseStatus = "new"
)

// Defines values for HealthResponseStatus.
const (
	Ok          HealthResponseStatus = "ok"
	Unavailable HealthResponseStatus = "unavailable"
)

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Headers *map[string]string `json:"headers,omitempty"`
	Method  string             `json:"method"`
	Url     string             `json:"url"`
}

// CreateTaskResponse defines model for CreateTaskResponse.
type CreateTaskResponse struct {
	Id *string `json:"id,omitempty"`
}

// DeleteTaskResponse defines model for DeleteTaskResponse.
type DeleteTaskResponse struct {
	HttpStatusCode *int    `json:"httpStatusCode,omitempty"`
	Id             *string `json:"id,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// GetAllTasksResponse defines model for GetAllTasksResponse.
type GetAllTasksResponse struct {
	Tasks *[]GetTaskResponse `json:"tasks,omitempty"`
}

// GetTaskResponse defines model for GetTaskResponse.
type GetTaskResponse struct {
	Headers        *map[string][]string   `json:"headers,omitempty"`
	HttpStatusCode *int                   `json:"httpStatusCode,omitempty"`
	Id             *string                `json:"id,omitempty"`
	Length         *int64                 `json:"length,omitempty"`
	Status         *GetTaskResponseStatus `json:"status,omitempty"`
}

// GetTaskResponseStatus defines model for GetTaskResponse.Status.
type GetTaskResponseStatus string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Port   *string               `json:"port,omitempty"`
	Status *HealthResponseStatus `json:"status,omitempty"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// PostTaskJSONRequestBody defines body for PostTask for application/json ContentType.
type PostTaskJSONRequestBody = CreateTaskRequest

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYUW/bNhD+KwS3R9lSbKdp/JalRWJgD0bqPQXGwIgniw1FqiTlzA3834cj7Viy5Nod",
	"ljYD9hILIo/33X3fHU95pqkuSq1AOUvHz9SmORTMP14bYA5mzD7ewZcKrMOXpdElGCfAb8mBcTD+kXEu",
	"nNCKyWlji1uVQMfUOiPUgq4jCn+xopSAa1eVy7URXxka0jGdgXVkhJs2VvrhM6QOXxTgcs3R6MWe3nyc",
	"0ajtoDKyuS93rrTjOMbfB6H62iziBbi27TqiBr5UwgCn4/utz3DivANUPUO21MpCO0ViD3T6PmMXQ857",
	"g3POeqPhxaDHLi6zXvZ+9C5LUjhLU96JrOX9A0g45h1D/uSYq+y15tBAMkiSl0OFcrAAg6e+Ht6Pxmhz",
	"GCrgctO3UEsmBSd/3P1+mosbcFdSYkrsYUcOlz01Dgr/8KuBjI7pL/GuFuJNIcQ34Bop3rllxrDVQRxH",
	"eDleOC/oWgJv+m9U1LVWDpTrzfyWe8rKUorU11f82WpF511wf5ZKIipBLVzeOGuYnEc006ZgLvh8N6Jd",
	"EKwH7E1VVWCwCp5oRIX6szQ6BWtpRLlWQKONtua1VG1XThDVLTDp8sNcltq4ZjYuk8uzrmjbkPUjthfF",
	"lkxI9iChidGvHkWIr4TKNJ7LwaZGlJt+ejWdkEwbkmKfEmpBbmezKfH67+PJwnk3/i3qldxVSoEhV9MJ",
	"jegSjA3nnPWTfoIB6BIUKwUd02E/6Q9pREvmch9RnPs0fcVnbK4tMHfgKqMsGSQJ0UquyFMOigQrkuaQ",
	"PpISMQpLbJUif1kl+2Rrdp4M2xZgcHstf0SbcErGhPRBIlNe/xOOVwa42w1O7PWBUo9/kCT4k4YC8oW5",
	"Xzs7jr2FfsS/SyYr2Mlgy/2WatzlGQr95Fi32dOat2ym8ROYpUgB4w6ZWPWRmfNk+J3w66o7IY769tcK",
	"qOaj75Vuq6JgZoUarbGO0mULi/UTUkDnuDlGYYcIbIf+wmVtCSMKngizK5XmRitd2V1ZtAUz1da3chpG",
	"A7DuN81XJ6T6tPS0Z6x1cwpxpoL1P5Lq9wM4zJFvDr6LAPdyG/2LEJpzQYf3yWYM2BCw0fsPBeDAKCaJ",
	"BbMEQ/x1sq/QkEkvo5pAw7Cx02f8LPg6iBOnt7ZMw1RniVbhLPKwIpMPbWHupr8J933YsAKcnynun6nA",
	"o7A304gqVvirk9N9YdWLeP+amb+i6Dom10OiC2n6iaLzHCABHsDoxwHw4SvtSKYrxd+o6AOTNaF2SD/6",
	"9jxwTOibWfq/p/LWl8MBjnf8/i/wNyfwG3DfVve2sdujgy+Tcjd7d2rc0teVY+vb+BArUrzZaxYJeclk",
	"Fx+429uHHuH/G+S/cMdxLHXKZK6tG/vxdj1f/x0AAP//KUBLDAATAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
